language: python
sudo: false
python:
- '3.6'
matrix:
  include:
  - python: 3.7
    dist: xenial
install:
- pip install -r requirements/requirements-travis.txt
script:
- tox
deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: "ERvy8lZ3UL1S0ZvfbA27qiMxe+iOA4oAKd8yt0wwwZdJ3I7UfDQBiY7TiV/M6raHYcn71dmdZrvgnXo4gPF4gjKJ/6Z0u4v9LVrxpzB97EVOwx6NapzB3a6SpBpay368KyvaKc9y5v6QNPi+j8A3CV0CzqDcYqOubjd1NCIDsmy0/Fw3VRyTr3/P/nTgcINzejn0oDZ1K90AdQlW0NLPLSn8wWAvzEHy319dlKlStk7LllG+mZ0p8Us1FO6Wd8XYh/UcbEnOHfrc3GO20uX7OoWZeYLAqUGszc1Z9fedZoGnn6lbW0vpJGO1UfODjNacQ6Ns6QBbrgGcYc8SAXMysR4/Lz07hTpSS3pwX1PKEWTf+tAR8wtGqq77gU38i7CNf24MS/+/ZPbN1OFRcSeRYATN1vytv539kLF94LqZKfzAczX9N+QDHSgphGzG8cFpsyHz+cZQvTqNkkIsORLxAmoFn1lw/zuIFNmKzxiuIQc5SlHqOoaNcbXCMDwjtx6CpbeNGQw2bi9mK8wre7zu75qZubry8Z4MZ1Csa1iw3r9n3y+esXVH+fiOQkBXL44DpGGny6FaKRPBgYRj6OF/alDA49/fgq9vZjz2F5fACRSF3Od/sDzOhFwYXCF0MkgAG+wrXvTAaFZjuZ7jfvEbWrKTcmNfp1hAvl4OQ7SOwZM="
  distributions: sdist bdist_wheel
