language: python
sudo: false
python:
- '3.6'
matrix:
  include:
  - python: 3.7
    dist: xenial
install:
- pip install -r requirements/requirements-travis.txt
script:
- tox
deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: "PBTxH+pi0GNztu9yX/AiaQuqNgB/lrgcR1LLGkwJggtNKJaL5Fxb6dT8T4BWPDr+A2UdtL8VrlsW5Mn5ci/R+qmtUU6BRCK7mX22W21wKXjSrKxTIQE+kqe2cE/U8DCTVRdwrrtJRG30I7SmuJujpNvAncoDsRepOceC6hCSd0l8r6nPfxc0eGulv5hzaum7soC6hdAqV6dU5ksRYeMJHupscTeonJJAGJeJW9xT+F2+i203ez5+b+tF4QWAoxgpABD+y0evX1D781qnupyQOf/wzVigKjMiOZlCAZx0O6YJY3bEw9IUG6c67gq7fI+N6+ZPtpK+VDsYZHbdxUNTDZiTG/OE4fYn8TjEi21cqGejwMRG9xSUjSe0AhZXlKad3kj2eE/EP1WvLf0rQbep4TcS3NHmg+1uKXsvvLwNXH2V4u8SSxO1PU1835gffDNMul3Nm14o9d3mGIB61qxjeVLu9zpupJ1NgFGF7Hak3PjbRxxCVOgwpPL4ZXKZk7K2rcmn8kkFYM4CZ9gasIWz4PqPu1qQ4NmuxqgEryBQakSoBbC9KUj46dH2LB+iN4/lPb5+LSGz1fG6zyVL6AWkEtizUU/QkxImzU/+m+c76AQ9vDVqOQS3oZ5dPjjalpSIaEEJsluLbcBJYlX/BQwCOBLLYQoor+0fagyezh+mnr4="
  distributions: sdist bdist_wheel
