language: python
sudo: false
python:
- '3.6'
matrix:
  include:
  - python: 3.7
    dist: xenial
install:
- pip install -r requirements/requirements-travis.txt
script:
- tox
deploy:
  provider: pypi
  username: __token__
  password:
    secure: OuLtD/1kpoXMGxbwL25Oy5icGiFgnG5UYYyY4220w+IXW33vn2PlC9v0MhL60S6j17LkwNwRawYtiFlBs9XUL30YSLz4Z5WjudFkfkdqbeQIFVF/WmMW9GhgT6AFYUJFghPXSD4cQlgSc4AW5E7wX1tCIHExHrQW1E3pfX0BE/9WCi+rE+3IZvrXXexGuZpjgEngDpqb7M5sODjPqy2EBX916nElXcljQFFGbmJNR2/MQAaRcJAHvwz0aRpMs8hbibcSGvf6clRpL3X1u9W1+iouBawdUDWVYEd5UfI7i594yNIT0uWjPTYfKo60Ax2H2tbU6Zc8xZHNRfG/JkkdkLWKfx73duXy7mXUK3NhRZWEoQ3sL/nD6BjE0RXOISSX+lQbhPtYmVdXBPbLWL1hrBNjSgwmQCNz5U3Fask/RIfB55scPyCegO+DdOUvQPkL1IcDFHJHx5KdjFo7X3LjBrRJmSPynHwnln84oC+Pc4v9+iZRN+t9S50HfjecRpFPhStQK4JqEh/lhIuj4xRvKex0BhSXttuvQthq8Zs2S4lRhgr6dHj4H4uPK36EzO5WkZHK0Z3SYJc3Ap85HANZlLmQKOzWXCtf88jRvPEIZHeiaC6h3xaF969LlrakVrXxn89hCPObGKw8ZykffFmEx25wTBtK3fJ2MuPKzZthonA=
  distributions: sdist bdist_wheel
