language: python
sudo: false
python:
- '3.6'
matrix:
  include:
  - python: 3.7
    dist: xenial
install:
- pip install -r requirements/requirements-travis.txt
script:
- tox
deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: "aJpZBFZIulO2v6kYaE6dRR99W92EDuf/oy7v0VPhaTxo8dwWVhiRWgLgSnjHKD7/uQIBd5hc9kfKHq3EtlrAPyZ8WIgy56vJ9jHVbtc67BhQSOgyIaGxmCrHUDsNPtMxmGYEm9nR/72zpS3zKVd2/faQt5bZDVzcKAMTSH83FMIQ8GCvZSzJIWVkqWPC9fo9K6K3jiby2lE+G6Jr/94NW2fVhzmsCv3iYjv0QNtbCmXMfGBlMueIfvt/e/sXxGFyUxIcttHVqYJ+osnuUq8YsHvhl2YquS7/ZtBQVFn1G57Pkm/aI8pln1jRcCSnomlTKJkXNRIVxWq33lZ0PKHZM4mt4SMgxCkNLD7XQfNuldGL+py/DXhHiRARLPexuG7skiv3MhGDOtar2S9y/KB5STpsq25UpJ3RQJy6WJULSngU+Od4ND5NgLuKN+jMarucqecEyk9Z6ya+aHMlM1bj+e8rBZYv1lANoKGnHEcj3xJW1ZkgDq3DRj4yxN5cKft6v1Gq0ucqXMzTzZsnY+cyVw943cJyXv4BS6Nli/36S+JSZCDsTCPJ9KgjHT1xulWm1FwoAXrnV8PQzd2nkLWDgqQUep0sGihv11iMJ7NK4JSkyhqabURQCWZyv5Rw23tMBez352Yo6q9JwbM+uTqjSdKb3Wn1+SshRaKWEU+0dxs="
  distributions: sdist bdist_wheel
