language: python
sudo: false
python:
- '3.6'
matrix:
  include:
  - python: 3.7
    dist: xenial  # https://github.com/travis-ci/travis-ci/issues/9815
    sudo: true
  - python: 3.6
    env: TOXENV=lint
  - python: 3.6
    env: TOXENV=style
  - python: 3.6
    env: TOXENV=types
install:
- pip install -r requirements/requirements-travis.txt
script:
- tox
deploy:
  provider: pypi
  username: __token__
  password:
    secure: PbDDDx/BiT4e3+KGuMEjITuw+eefURP7HUliKam49AQQi1fEw1gzTrgVHEUfpdnTLGJFVOauTcCMq2jarsrUdiRKLTmgvQvc52seNxiCsj+RUp1xoecZZ+iDyKy0Co2uOYhq7YzlNhmpS/I9cIk759NHE+IwY4zxdiSqb+shTwLSvCx/aIX5BMhO2tNLHRjVLQgDQsVTZhUzOnBoQHrQ5K+v00NirkgITJNVsBtj6B1v0eZ7V25O5cSE0R58CTi6fd/bu5nb/PKCXInyZYA+7VWjaB4gL5b140tFn9lFKIh8zjiR683reHLyizLlKIUTxcXTAZ0hpRZGTVXW/KJIs5FS+btrAG9ij8L8ImpiCWnke42sA+riDa2F6xwMMtNf+YmmvEOcXPaZ8y982FDa2PxTt4GOnyccOvgltdbUSv5GvylnKozPz5z+4rOwa177veEp3Td/hftVMC4wbGNHROdg+YlhUSFHgsBzgWIGH3HjzLsmwIcW8f3lkcTEbm1lrageWATBWuS9jjzKOvOZrv2iWpx2XdI59WR0QyNlT8YFSCH2ZG1Yv2Icste8m1sG2B8wHcd/XQH4UQVR2RmbzIK+a16oLPt/t6I1XwKc6vguvFVSFbcMKKlj48J6+ZsrnFPYxv9FBTwbYIBgAFnly3ZfCbwMgWX+Vk5MmEcwWoA=
  distributions: sdist bdist_wheel
  on:
    branch: master
